before_install:
  - sudo apt-get install -y wget openssl libssl-dev coreutils
  - sudo apt-get install -y build-essential ca-certificates
  - wget -O /tmp/openssl-1.0.2h.tar.gz https://www.openssl.org/source/openssl-1.0.2h.tar.gz
  - cd /tmp/ && tar -xf /tmp/openssl-1.0.2h.tar.gz
  - rm /tmp/openssl-1.0.2h.tar.gz
  - cd /tmp/openssl-1.0.2h && ./config
  - cd /tmp/openssl-1.0.2h && make depend
  - cd /tmp/openssl-1.0.2h && make
  - cd /tmp/openssl-1.0.2h && sudo make install
  - rm -R /tmp/openssl-1.0.2h
language: node_js
env:
  - CXX=g++-4.8
node_js:
  - '6.2'
  - '5.1'
  - '4.2'
  - '0.12'
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
